#!/usr/bin/env bash

# Fail immediately if any errors occur
set -e

clear

echo "Caching password..."
sudo -K
sudo true;

echo
if hash brew 2>/dev/null; then
  echo "Homebrew is already installed!"
else
  echo "Installing Homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo
echo "Ensuring you have the latest Homebrew..."
brew update

echo
echo "Ensuring your Homebrew directory is writable..."
sudo chown -R $(whoami) /usr/local/bin

echo
echo "Installing Homebrew services..."
brew tap homebrew/services

echo
echo "Upgrading existing brews..."
brew upgrade

echo
echo "Cleaning up your Homebrew installation..."
brew cleanup

brew cask install iterm2
brew cask install shiftit

echo
echo "Setup complete!"
echo

